"""创建User Model

Revision ID: 7e9e8cdd10ed
Revises: 
Create Date: 2020-12-10 22:51:47.400892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9e8cdd10ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_email', sa.String(length=64), nullable=True),
    sa.Column('_username', sa.String(length=64), nullable=True),
    sa.Column('_password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.TEXT(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMAle', 'SECRET', name='genderenum'), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('_phone', sa.String(length=11), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__email'), 'user', ['_email'], unique=True)
    op.create_index(op.f('ix_user__username'), 'user', ['_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__username'), table_name='user')
    op.drop_index(op.f('ix_user__email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
