"""empty message

Revision ID: b77d97f7acfb
Revises: 7e9e8cdd10ed
Create Date: 2020-12-13 22:15:02.681270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77d97f7acfb'
down_revision = '7e9e8cdd10ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysresource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sysresource_create_at'), 'sysresource', ['create_at'], unique=False)
    op.create_index(op.f('ix_sysresource_update_at'), 'sysresource', ['update_at'], unique=False)
    op.create_table('sysrole',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sysrole_create_at'), 'sysrole', ['create_at'], unique=False)
    op.create_index(op.f('ix_sysrole_update_at'), 'sysrole', ['update_at'], unique=False)
    op.create_table('role_resource',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource.id'], ['sysresource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sysrole.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'resource.id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role__id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role__id'], ['sysrole.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role__id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('role_resource')
    op.drop_index(op.f('ix_sysrole_update_at'), table_name='sysrole')
    op.drop_index(op.f('ix_sysrole_create_at'), table_name='sysrole')
    op.drop_table('sysrole')
    op.drop_index(op.f('ix_sysresource_update_at'), table_name='sysresource')
    op.drop_index(op.f('ix_sysresource_create_at'), table_name='sysresource')
    op.drop_table('sysresource')
    # ### end Alembic commands ###
